name: CI - DevSecOps Scans + Build

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  security-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1) Secret Scanning - Gitleaks
      - name: Gitleaks (secret scan)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2) SAST - Semgrep
      - name: Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/python

      # 3) SCA - Snyk (Dependency scan)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (for Snyk)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Snyk (SCA)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # 4) Build Docker Image
      - name: Set image name
        id: vars
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/devsecops-flask:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ${{ steps.vars.outputs.IMAGE }} .

      # 5) Container Scan - Trivy
      - name: Trivy (Container Scan)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ steps.vars.outputs.IMAGE }}
          format: table
          exit-code: "1"
          severity: "CRITICAL,HIGH"

      # 6) Push image (only main branch, only if scans passed)
      - name: Push image to GHCR
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ steps.vars.outputs.IMAGE }}
